import Link from "next/link";
import "./globals.css";
import type { Metadata } from "next";
import style from "./layout.module.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body>
        <nav>
          <div className={style.navContainer}>
            <h1>Crud com Spring Boot e Next.js </h1>
            <ul>
              <li>
                <Link href="/">Lista de produtos</Link>
              </li>
              <li>
                <Link href="/create">Cadastrar Produto</Link>
              </li>
              <li>
                <Link href="/update">Atualizar Produto</Link>
              </li>
              <li>
                <Link href="/delete">Excluir Produto</Link>
              </li>
            </ul>
          </div>
        </nav>
        <hr />
        {children}
      </body>
    </html>
  );
}
